/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as BrandingIndexRouteImport } from './routes/branding.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as BrandingLogoSketchesRouteImport } from './routes/branding.logo-sketches'
import { Route as ArticleSlugRouteImport } from './routes/article.$slug'
import { Route as AdminToolsRouteImport } from './routes/admin.tools'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminInstagramRouteImport } from './routes/admin.instagram'
import { Route as AdminHomepageRouteImport } from './routes/admin.homepage'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminBusinessRouteImport } from './routes/admin.business'
import { Route as AdminServicesIndexRouteImport } from './routes/admin.services.index'
import { Route as ApiPublicIndexnowRouteImport } from './routes/api/public/indexnow'
import { Route as AdminServicesSlugRouteImport } from './routes/admin.services.$slug'
import { Route as AdminPreviewSlugRouteImport } from './routes/admin.preview.$slug'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicHooksAutopilotDailyRouteImport } from './routes/api/public/hooks/autopilot-daily'

const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandingIndexRoute = BrandingIndexRouteImport.update({
  id: '/branding/',
  path: '/branding/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandingLogoSketchesRoute = BrandingLogoSketchesRouteImport.update({
  id: '/branding/logo-sketches',
  path: '/branding/logo-sketches',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleSlugRoute = ArticleSlugRouteImport.update({
  id: '/article/$slug',
  path: '/article/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminToolsRoute = AdminToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInstagramRoute = AdminInstagramRouteImport.update({
  id: '/instagram',
  path: '/instagram',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomepageRoute = AdminHomepageRouteImport.update({
  id: '/homepage',
  path: '/homepage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBusinessRoute = AdminBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesIndexRoute = AdminServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicIndexnowRoute = ApiPublicIndexnowRouteImport.update({
  id: '/api/public/indexnow',
  path: '/api/public/indexnow',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminServicesSlugRoute = AdminServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPreviewSlugRoute = AdminPreviewSlugRouteImport.update({
  id: '/preview/$slug',
  path: '/preview/$slug',
  getParentRoute: () => AdminRoute,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAutopilotDailyRoute =
  ApiPublicHooksAutopilotDailyRouteImport.update({
    id: '/api/public/hooks/autopilot-daily',
    path: '/api/public/hooks/autopilot-daily',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/knowledge': typeof KnowledgeRoute
  '/privacy': typeof PrivacyRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/admin/business': typeof AdminBusinessRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/instagram': typeof AdminInstagramRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/tools': typeof AdminToolsRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/branding/logo-sketches': typeof BrandingLogoSketchesRoute
  '/category/$slug': typeof CategorySlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/branding/': typeof BrandingIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/admin/preview/$slug': typeof AdminPreviewSlugRoute
  '/admin/services/$slug': typeof AdminServicesSlugRoute
  '/api/public/indexnow': typeof ApiPublicIndexnowRoute
  '/admin/services/': typeof AdminServicesIndexRoute
  '/api/public/hooks/autopilot-daily': typeof ApiPublicHooksAutopilotDailyRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/contact': typeof ContactRoute
  '/knowledge': typeof KnowledgeRoute
  '/privacy': typeof PrivacyRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/admin/business': typeof AdminBusinessRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/instagram': typeof AdminInstagramRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/tools': typeof AdminToolsRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/branding/logo-sketches': typeof BrandingLogoSketchesRoute
  '/category/$slug': typeof CategorySlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/branding': typeof BrandingIndexRoute
  '/services': typeof ServicesIndexRoute
  '/admin/preview/$slug': typeof AdminPreviewSlugRoute
  '/admin/services/$slug': typeof AdminServicesSlugRoute
  '/api/public/indexnow': typeof ApiPublicIndexnowRoute
  '/admin/services': typeof AdminServicesIndexRoute
  '/api/public/hooks/autopilot-daily': typeof ApiPublicHooksAutopilotDailyRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/knowledge': typeof KnowledgeRoute
  '/privacy': typeof PrivacyRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/admin/business': typeof AdminBusinessRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/instagram': typeof AdminInstagramRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/tools': typeof AdminToolsRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/branding/logo-sketches': typeof BrandingLogoSketchesRoute
  '/category/$slug': typeof CategorySlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/branding/': typeof BrandingIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/admin/preview/$slug': typeof AdminPreviewSlugRoute
  '/admin/services/$slug': typeof AdminServicesSlugRoute
  '/api/public/indexnow': typeof ApiPublicIndexnowRoute
  '/admin/services/': typeof AdminServicesIndexRoute
  '/api/public/hooks/autopilot-daily': typeof ApiPublicHooksAutopilotDailyRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessibility'
    | '/admin'
    | '/contact'
    | '/knowledge'
    | '/privacy'
    | '/rss.xml'
    | '/sitemap'
    | '/sitemap.xml'
    | '/terms'
    | '/thank-you'
    | '/admin/business'
    | '/admin/categories'
    | '/admin/content'
    | '/admin/gallery'
    | '/admin/homepage'
    | '/admin/instagram'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/media'
    | '/admin/reviews'
    | '/admin/tools'
    | '/article/$slug'
    | '/branding/logo-sketches'
    | '/category/$slug'
    | '/services/$slug'
    | '/admin/'
    | '/branding/'
    | '/services/'
    | '/admin/preview/$slug'
    | '/admin/services/$slug'
    | '/api/public/indexnow'
    | '/admin/services/'
    | '/api/public/hooks/autopilot-daily'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessibility'
    | '/contact'
    | '/knowledge'
    | '/privacy'
    | '/rss.xml'
    | '/sitemap'
    | '/sitemap.xml'
    | '/terms'
    | '/thank-you'
    | '/admin/business'
    | '/admin/categories'
    | '/admin/content'
    | '/admin/gallery'
    | '/admin/homepage'
    | '/admin/instagram'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/media'
    | '/admin/reviews'
    | '/admin/tools'
    | '/article/$slug'
    | '/branding/logo-sketches'
    | '/category/$slug'
    | '/services/$slug'
    | '/admin'
    | '/branding'
    | '/services'
    | '/admin/preview/$slug'
    | '/admin/services/$slug'
    | '/api/public/indexnow'
    | '/admin/services'
    | '/api/public/hooks/autopilot-daily'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accessibility'
    | '/admin'
    | '/contact'
    | '/knowledge'
    | '/privacy'
    | '/rss.xml'
    | '/sitemap'
    | '/sitemap.xml'
    | '/terms'
    | '/thank-you'
    | '/admin/business'
    | '/admin/categories'
    | '/admin/content'
    | '/admin/gallery'
    | '/admin/homepage'
    | '/admin/instagram'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/media'
    | '/admin/reviews'
    | '/admin/tools'
    | '/article/$slug'
    | '/branding/logo-sketches'
    | '/category/$slug'
    | '/services/$slug'
    | '/admin/'
    | '/branding/'
    | '/services/'
    | '/admin/preview/$slug'
    | '/admin/services/$slug'
    | '/api/public/indexnow'
    | '/admin/services/'
    | '/api/public/hooks/autopilot-daily'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccessibilityRoute: typeof AccessibilityRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  KnowledgeRoute: typeof KnowledgeRoute
  PrivacyRoute: typeof PrivacyRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SitemapRoute: typeof SitemapRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ThankYouRoute: typeof ThankYouRoute
  ArticleSlugRoute: typeof ArticleSlugRoute
  BrandingLogoSketchesRoute: typeof BrandingLogoSketchesRoute
  CategorySlugRoute: typeof CategorySlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  BrandingIndexRoute: typeof BrandingIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  ApiPublicIndexnowRoute: typeof ApiPublicIndexnowRoute
  ApiPublicHooksAutopilotDailyRoute: typeof ApiPublicHooksAutopilotDailyRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branding/': {
      id: '/branding/'
      path: '/branding'
      fullPath: '/branding/'
      preLoaderRoute: typeof BrandingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branding/logo-sketches': {
      id: '/branding/logo-sketches'
      path: '/branding/logo-sketches'
      fullPath: '/branding/logo-sketches'
      preLoaderRoute: typeof BrandingLogoSketchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/$slug': {
      id: '/article/$slug'
      path: '/article/$slug'
      fullPath: '/article/$slug'
      preLoaderRoute: typeof ArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tools': {
      id: '/admin/tools'
      path: '/tools'
      fullPath: '/admin/tools'
      preLoaderRoute: typeof AdminToolsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/instagram': {
      id: '/admin/instagram'
      path: '/instagram'
      fullPath: '/admin/instagram'
      preLoaderRoute: typeof AdminInstagramRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/homepage': {
      id: '/admin/homepage'
      path: '/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AdminHomepageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/business': {
      id: '/admin/business'
      path: '/business'
      fullPath: '/admin/business'
      preLoaderRoute: typeof AdminBusinessRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services/': {
      id: '/admin/services/'
      path: '/services'
      fullPath: '/admin/services/'
      preLoaderRoute: typeof AdminServicesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/indexnow': {
      id: '/api/public/indexnow'
      path: '/api/public/indexnow'
      fullPath: '/api/public/indexnow'
      preLoaderRoute: typeof ApiPublicIndexnowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/services/$slug': {
      id: '/admin/services/$slug'
      path: '/services/$slug'
      fullPath: '/admin/services/$slug'
      preLoaderRoute: typeof AdminServicesSlugRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/preview/$slug': {
      id: '/admin/preview/$slug'
      path: '/preview/$slug'
      fullPath: '/admin/preview/$slug'
      preLoaderRoute: typeof AdminPreviewSlugRouteImport
      parentRoute: typeof AdminRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/autopilot-daily': {
      id: '/api/public/hooks/autopilot-daily'
      path: '/api/public/hooks/autopilot-daily'
      fullPath: '/api/public/hooks/autopilot-daily'
      preLoaderRoute: typeof ApiPublicHooksAutopilotDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminBusinessRoute: typeof AdminBusinessRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminHomepageRoute: typeof AdminHomepageRoute
  AdminInstagramRoute: typeof AdminInstagramRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminToolsRoute: typeof AdminToolsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPreviewSlugRoute: typeof AdminPreviewSlugRoute
  AdminServicesSlugRoute: typeof AdminServicesSlugRoute
  AdminServicesIndexRoute: typeof AdminServicesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBusinessRoute: AdminBusinessRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminContentRoute: AdminContentRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminHomepageRoute: AdminHomepageRoute,
  AdminInstagramRoute: AdminInstagramRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminToolsRoute: AdminToolsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminPreviewSlugRoute: AdminPreviewSlugRoute,
  AdminServicesSlugRoute: AdminServicesSlugRoute,
  AdminServicesIndexRoute: AdminServicesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccessibilityRoute: AccessibilityRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  KnowledgeRoute: KnowledgeRoute,
  PrivacyRoute: PrivacyRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SitemapRoute: SitemapRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ThankYouRoute: ThankYouRoute,
  ArticleSlugRoute: ArticleSlugRoute,
  BrandingLogoSketchesRoute: BrandingLogoSketchesRoute,
  CategorySlugRoute: CategorySlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  BrandingIndexRoute: BrandingIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  ApiPublicIndexnowRoute: ApiPublicIndexnowRoute,
  ApiPublicHooksAutopilotDailyRoute: ApiPublicHooksAutopilotDailyRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
